[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -DASYNCWEBSERVER_REGEX
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    esphome/ESPAsyncWebServer-esphome
    esphome/ESPAsyncTCP-esphome
    ArduinoJson
lib_ldf_mode = chain+
board_build.filesystem = littlefs
upload_protocol = espota
upload_port = 10.0.0.215
upload_flags = 
	--auth=bell
	--timeout=30
	--host_port=44444
